### ISSUE TITLE
Feedback on week 9 project progress

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t11-1/main#47]
Subject: feedback on week 9 project progress

See [v1.2 progress guide](https://nuscs2113-ay1819s2.github.io/website/admin/project-w09-v12.html) for more details of the activities mentioned below.

### Recommended progress for v1.2

-  [x]  Issue labels<sup>*</sup> set up e.g., `type.*` and `priority.*` (:heavy_check_mark: well done!)
-  [x]  All milestones `v1.2`, `v1.3`, `v1.4`, created (:heavy_check_mark: well done!)
-  [x]  Issues marked as `type.Story` e.g., [link](https://github.com/CS2113-AY1819S2-T11-1/main/issues/14) (:heavy_check_mark: well done!)
-  [x]  Some issues prioritized using `priority.*` labels e.g., [link](https://github.com/CS2113-AY1819S2-T11-1/main/issues/14) (:heavy_check_mark: well done!)
*  Milestone v1.2 _managed_ systematically
     -  [x]  A suitable deadline<sup>**</sup> set (:heavy_check_mark: well done!)
     -  [x]  Issues allocated to v1.2 e.g., [link](https://github.com/CS2113-AY1819S2-T11-1/main/issues/19) (:heavy_check_mark: well done!) 
     -  [x]  All issues/PRs in it are closed/merged  (:heavy_check_mark: well done!) 
     -  [x]  Milestone closed (:heavy_check_mark: well done!) 
     -  [ ]  Code tagged as `v1.2` (:exclamation: try to do by next milestone) 
-  [x]  Build passing [link](https://travis-ci.org/CS2113-AY1819S2-T11-1/main/builds/507911346) (:heavy_check_mark: well done!)
-  [x]  Some issues assigned to milestone v1.3 e.g., [link](https://github.com/CS2113-AY1819S2-T11-1/main/issues/34) (:heavy_check_mark: well done!)

 <sup>*</sup>Remember to use the format specified, else it will not be picked up by the bot
<sup>**</sup>Remember that the deadline is the midnight before your tutorials

Not graded:
- [x] Updated User Guide for v1.2  (:+1:  Kudos!)

### Recommended progress for v1.2

  - [ ]  Merged updates to java/fxml files (:exclamation: try to do by next milestone)
  - [ ]  Merged updates to the Developer Guide (:exclamation: try to do by next milestone)
  - [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)

### Recommended progress for v1.2

  - [x]  Merged updates to java/fxml files (:heavy_check_mark: well done!)
  - [x]  Merged updates to the Developer Guide (:heavy_check_mark: well done!)
  - [x]  Has issues/PRs assigned for the milestone (:heavy_check_mark: well done!)

Tutor: @stephlewyh

Note: the above observation was done by the CS2113-feedback-bot and covers changes up to 2019-03-19 00:00:00 only. If you think the above observation is incorrect, please let us know by replying in this thread. Please include links to relevant PRs/comments in your response.
